[tool.poetry]
name = "escape-hatch"
version = "0.1.0"
description = ""
authors = ["Adrian Causby"]

[tool.poetry.dependencies]
python = "^3.6.2"
pynput = "*"
black = "^22.3.0"
tensorflow = "*"



[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
